<a href="https://colab.research.google.com/github/shabeeb248/Guvi-Assignment-Task-7/blob/main/DataPreprocessing_Assignment11_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Data.csv

**Step 1: Importing the libraries**

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


**Step 2: Importing dataset**

In [ ]:
df=pd.read_csv('/content/Data.csv')
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
df.shape

(10, 4)

**Step 3: Handling the missing data**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [ ]:
df.dropna()

Country   Age   Salary  Purchased
0        0  44.0  72000.0          0
1        2  27.0  48000.0          1
2        1  30.0  54000.0          0
3        2  38.0  61000.0          0
5        0  35.0  58000.0          1
7        0  48.0  79000.0          1
8        1  50.0  83000.0          0
9        0  37.0  67000.0          1

In [ ]:
X = df.iloc[:, :3].values
Y = df.iloc[:, 3:4].values

**Step 4: Encoding categorical data**

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
df['Country']= le.fit_transform(df['Country'])
le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print(le_name_mapping)

{'France': 0, 'Germany': 1, 'Spain': 2}


In [ ]:
df['Purchased']= le.fit_transform(df['Purchased'])
le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print(le_name_mapping)

{'No': 0, 'Yes': 1}


**Step 5: Creating a dummy variable**

In [ ]:
# Encoding independent variable
dummy1 = pd.get_dummies(df['Country'])
dummy1

0  1  2
0  1  0  0
1  0  0  1
2  0  1  0
3  0  0  1
4  0  1  0
5  1  0  0
6  0  0  1
7  1  0  0
8  0  1  0
9  1  0  0

In [ ]:
df = pd.concat([df,dummy1], axis=1)
df

Country   Age   Salary  Purchased  0  1  2
0        0  44.0  72000.0          0  1  0  0
1        2  27.0  48000.0          1  0  0  1
2        1  30.0  54000.0          0  0  1  0
3        2  38.0  61000.0          0  0  0  1
4        1  40.0      NaN          1  0  1  0
5        0  35.0  58000.0          1  1  0  0
6        2   NaN  52000.0          0  0  0  1
7        0  48.0  79000.0          1  1  0  0
8        1  50.0  83000.0          0  0  1  0
9        0  37.0  67000.0          1  1  0  0

In [ ]:
dummy = df.iloc[:,4:].values
dummy

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=uint8)

In [ ]:
np.concatenate([dummy,X[:,1:]],axis = 1)

array([[1.0e+00, 0.0e+00, 0.0e+00, 4.4e+01, 7.2e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.7e+01, 4.8e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.8e+01, 6.1e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 4.0e+01,     nan],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.5e+01, 5.8e+04],
       [0.0e+00, 0.0e+00, 1.0e+00,     nan, 5.2e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.8e+01, 7.9e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.7e+01, 6.7e+04]])

In [ ]:
#Encoding dependent variable
dummy2 = pd.get_dummies(df['Purchased'])
dummy2

0  1
0  1  0
1  0  1
2  1  0
3  1  0
4  0  1
5  0  1
6  1  0
7  0  1
8  1  0
9  0  1

**Step 6: Splitting the datasets into training sets and Test sets**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)


In [ ]:
print(X_train,y_train)

[[1.0e+00 4.0e+01     nan]
 [0.0e+00 3.7e+01 6.7e+04]
 [2.0e+00 2.7e+01 4.8e+04]
 [2.0e+00     nan 5.2e+04]
 [0.0e+00 4.8e+01 7.9e+04]
 [2.0e+00 3.8e+01 6.1e+04]
 [0.0e+00 4.4e+01 7.2e+04]
 [0.0e+00 3.5e+01 5.8e+04]]    Purchased
4          1
9          1
1          1
6          0
7          1
3          0
0          0
5          1


In [ ]:
print(X_test, y_test)

[[1.0e+00 3.0e+01 5.4e+04]
 [1.0e+00 5.0e+01 8.3e+04]]    Purchased
2          0
8          0


**Step 7: Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(X_train)
x_test = sc_x.transform(X_test)